### ISSUE TITLE
Bootstrap dependency?

### ISSUE THREAD

**Issue by andriytyurnikov** [hung-phan/generator-mithril#1]
Running "browserify:app" (browserify) task

> > Error: Cannot find module 'bootstrap' from '/Users/andriytyurnikov/Code/teleport/mithril-yo/.tmp/jsx'
> > Warning: Error running grunt-browserify. Use --force to continue.

App was generated without twitter bootstrap

**Comment by hung-phan** [comment]
Hi @andriytyurnikov, I try to scaffold the app and it runs normally. I don't know what kind of problems you are getting right now, but I put all browserify's configuration in "root/browserify.config.js" to make them work like browserify-shim (hope so).

```
//third party libraries alias configurations for browserify
module.exports = [
    './app/bower_components/mithril/mithril.js:mithril',
    './app/bower_components/sass-bootstrap/dist/js/bootstrap.js:bootstrap',
    './app/bower_components/jquery/dist/jquery.js:jquery'
```

And the bootstrap dependencies, I inject them in "root/app/jsx/main.jsx" with this line.

```
require('bootstrap');
```

The errors you show earlier it could be that there is something wrong with the "browserify.config.js". Moreover, the folder "root/.tmp/jsx" I use to generate the template for jsx files and include in the main one using "grunt-include-replace" is shown in the errors as well. Maybe, this could be a problem if you use it wrong. Can you try it again?
